@panel panel1
dot1=[3,5];
circle1=circle([3,5],5);
circle2=circle([0,0],5);
printT(circle1);
printT(circle2);
printT(circle2.intersect(circle1));
printT(circle2.intersect(line([0,2],[1,2])));
printT(circle2.intersect(line([0,2],[1,2],-1,1)));
printT(circle2.intersect(line([0,-2],[0,2])));
printT(circle2.intersect(line([0,-2],[0,2],0,0)));
printT(circle1.getRadius());
printT(circle2.getCenter());
circle1.setCenter([2,2]);
printT(circle1);
circle2.setRadius(3);
printT(circle2);
printT(circle2.getPointbyarc(PI/4));
@end